---
# path or URL to sample sheet (TSV format, columns: sample, panel, ...)
samples: samples.tsv

# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: units.tsv

# Number of parts a fastq file should be split into
cgu_accel_num_fastq_split: 4

# Flag to force phred typ, can be removed to make trimmomatic determine score.
phread_flag: "-phred64"

# the sequencing adapter
illuminaclip_file: illumina.fa

# Accel Panel and the associated primer files
cgu_accel_panels:
  panel1:
    5p_primer_file: 5p_primers.fa
    3p_primer_file: 3p_primers.fa
  panel2:
    5p_primer_file: 5p_primers.fa
    3p_primer_file: 3p_primers.fa
